/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["operationsLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recent"];
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/error-class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitErrorClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bulk/{id}/items/{ordinal}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/definitions/{engineId}/{definitionId}/actions/{verb}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["definitionAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vitals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/actions/{verb}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instanceAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/actions/{verb}/curl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instanceActionCurl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instanceAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/change-state/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["executeChangeState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/change-state/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewChangeState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/diagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["diagram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/diff/{siblingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/jobs/external-worker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["externalWorkerJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/jobs/{jobId}/stacktrace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobStacktrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/nearest-sibling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["nearestSibling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["variables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{engineId}/{instanceId}/variables/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["variable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resolve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionCurlResponse: {
            curl?: string;
        };
        ActionRequest: {
            assignee?: string;
            confirmToken?: string;
            event?: components["schemas"]["EventTrigger"];
            executionId?: string;
            includeProcessInstances?: boolean;
            jobId?: string;
            reason?: string;
            taskId?: string;
            ticketId?: string;
            variable?: components["schemas"]["VariableEdit"];
            variables?: components["schemas"]["TypedVariable"][];
        };
        ActionResult: {
            /** Format: uuid */
            auditId?: string;
            correlationId?: string;
            deltaStatement?: string;
            /** Format: int32 */
            engineHttpStatus?: number;
            outcome?: string;
        };
        AuditEntryDto: {
            action?: string;
            actor?: string;
            breakGlass?: boolean;
            correlationId?: string;
            engineId?: string;
            /** Format: int32 */
            httpStatus?: number;
            /** Format: uuid */
            id?: string;
            instanceId?: string;
            outcome?: string;
            payload?: string;
            reason?: string;
            responseSnippet?: string;
            responseTruncated?: boolean;
            tenantId?: string;
            ticketId?: string;
            /** Format: date-time */
            ts?: string;
        };
        BulkErrorClassRequest: {
            /** Format: int32 */
            algoVersion?: number;
            /** Format: int32 */
            definitionVersion?: number;
            engineId?: string;
            processDefinitionKey?: string;
            reason?: string;
            signatureHash?: string;
            ticketId?: string;
        };
        BulkFilterRequest: {
            criteria?: components["schemas"]["SearchRequest"];
            reason?: string;
            ticketId?: string;
            verb?: string;
        };
        BulkItemDto: {
            /** Format: uuid */
            auditId?: string;
            detail?: string;
            engineId?: string;
            /** Format: date-time */
            finishedAt?: string;
            instanceId?: string;
            jobRef?: string;
            /** Format: int32 */
            ordinal?: number;
            state?: string;
        };
        BulkJobDto: {
            /** Format: uuid */
            continuedFrom?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: uuid */
            id?: string;
            items?: components["schemas"]["BulkItemDto"][];
            reason?: string;
            scopeKind?: string;
            scopeLabel?: string;
            state?: string;
            /** Format: date-time */
            submittedAt?: string;
            submittedBy?: string;
            tallies?: {
                [key: string]: number;
            };
            ticketId?: string;
            /** Format: int32 */
            totalItems?: number;
            verb?: string;
        };
        BulkSubmitRequest: {
            /** Format: uuid */
            continuedFrom?: string;
            items?: components["schemas"]["BulkTarget"][];
            reason?: string;
            ticketId?: string;
            verb?: string;
        };
        BulkTarget: {
            engineId?: string;
            instanceId?: string;
            jobId?: string;
        };
        ChangeStatePreview: {
            engineId?: string;
            enginePath?: string;
            method?: string;
            payload?: {
                [key: string]: unknown;
            };
            processDefinitionId?: string;
            processInstanceId?: string;
            simulationNote?: string;
            summary?: string;
            warnings?: components["schemas"]["Warning"][];
        };
        ChangeStateRequest: {
            reason?: string;
            sourceActivityIds?: string[];
            targetActivityIds?: string[];
            ticketId?: string;
        };
        CreateNote: {
            body: string;
        };
        CurrentActivity: {
            activityId?: string;
            activityName?: string;
            activityType?: string;
            startTime?: string;
        };
        EngineCapabilities: {
            activityHistory?: boolean;
            changeState?: boolean;
            externalWorkerJobs?: boolean;
            migration?: boolean;
            scopeType?: boolean;
        };
        EngineDto: {
            accentColor?: string;
            capabilities?: components["schemas"]["EngineCapabilities"];
            engineVersion?: string;
            environment?: string;
            healthError?: string;
            id?: string;
            jobLanes?: components["schemas"]["JobLanes"];
            lastHealthCheck?: string;
            mode?: string;
            name?: string;
            /** Format: int64 */
            oldestExecutableJobAge?: number;
            /** Format: int64 */
            overdueTimers?: number;
            reachable?: boolean;
            tenantId?: string;
        };
        EngineProbe: {
            error?: string;
            ok?: boolean;
        };
        EngineResult: {
            dlqScan?: string;
            error?: string;
            failingScan?: string;
            /** Format: int64 */
            fetched?: number;
            ok?: boolean;
            /** Format: int64 */
            total?: number;
        };
        ErrorGroup: {
            /** Format: int32 */
            algoVersion?: number;
            countsByEngine?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Format: int64 */
            deadLetterCount?: number;
            exceptionClass?: string;
            normalizedMessage?: string;
            /** Format: int64 */
            retryingCount?: number;
            sampleRawMessage?: string;
            signatureHash?: string;
            /** Format: int64 */
            total?: number;
        };
        EventTrigger: {
            name?: string;
            type?: string;
        };
        ExecutionScope: {
            activityId?: string;
            executionId?: string;
            parentExecutionId?: string;
            variables?: components["schemas"]["VariableDto"][];
        };
        ExternalWorkerJobDto: {
            createTime?: string;
            dueDate?: string;
            elementId?: string;
            elementName?: string;
            exceptionMessage?: string;
            executionId?: string;
            id?: string;
            lockExpirationTime?: string;
            lockOwner?: string;
            processDefinitionId?: string;
            /** Format: int32 */
            retries?: number;
            tenantId?: string;
        };
        HierarchyNode: {
            businessKey?: string;
            /** Format: int64 */
            childTotal?: number;
            children?: components["schemas"]["HierarchyNode"][];
            childrenTruncated?: boolean;
            definitionKey?: string;
            definitionName?: string;
            /** Format: int32 */
            definitionVersion?: number;
            endTime?: string;
            ended?: boolean;
            hasDeadLetterJobs?: boolean;
            processInstanceId?: string;
            requested?: boolean;
            startTime?: string;
        };
        InstanceDetail: {
            businessKey?: string;
            compositeId?: string;
            currentActivities?: components["schemas"]["CurrentActivity"][];
            definitionKey?: string;
            definitionName?: string;
            /** Format: int32 */
            definitionVersion?: number;
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            engineId?: string;
            /** Format: int32 */
            externalWorkerJobs?: number;
            flags?: components["schemas"]["InstanceStatusFlags"];
            processDefinitionId?: string;
            processInstanceId?: string;
            startTime?: string;
            startedBy?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "COMPLETED" | "FAILED" | "RETRYING";
            superProcessInstanceId?: string;
            telemetryUrl?: string;
            tenantId?: string;
            waitingFor?: components["schemas"]["WaitState"][];
            whyStuck?: components["schemas"]["WhyStuck"];
        };
        InstanceDiagram: {
            activeActivityIds?: string[];
            deadLetterActivityIds?: string[];
            xml?: string;
        };
        InstanceHierarchy: {
            /** Format: int32 */
            breadthCap?: number;
            depthLimitReached?: boolean;
            /** Format: int32 */
            maxDepth?: number;
            requestedProcessInstanceId?: string;
            root?: components["schemas"]["HierarchyNode"];
            rootProcessInstanceId?: string;
        };
        InstanceJobs: {
            deadLetter?: components["schemas"]["JobDto"][];
            executable?: components["schemas"]["JobDto"][];
            suspended?: components["schemas"]["JobDto"][];
            timer?: components["schemas"]["JobDto"][];
        };
        InstanceRef: {
            businessKey?: string;
            definitionId?: string;
            /** Format: int32 */
            definitionVersion?: number;
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            ended?: boolean;
            processDefinitionKey?: string;
            processInstanceId?: string;
            startTime?: string;
        };
        InstanceStatusFlags: {
            ended?: boolean;
            failedInSubprocess?: boolean;
            hasDeadLetterJobs?: boolean;
            hasFailingJobs?: boolean;
            suspended?: boolean;
        };
        InstanceTasks: {
            tasks?: components["schemas"]["TaskDto"][];
            /** Format: int64 */
            total?: number;
            truncated?: boolean;
        };
        InstanceTimeline: {
            activities?: components["schemas"]["TimelineActivity"][];
            /** Format: int64 */
            total?: number;
            truncated?: boolean;
        };
        InstanceVariables: {
            executionScopes?: components["schemas"]["ExecutionScope"][];
            processVariables?: components["schemas"]["VariableDto"][];
            source?: string;
        };
        JobDto: {
            createTime?: string;
            dueDate?: string;
            elementId?: string;
            elementName?: string;
            exceptionMessage?: string;
            executionId?: string;
            id?: string;
            lane?: string;
            processDefinitionId?: string;
            /** Format: int32 */
            retries?: number;
            tenantId?: string;
        };
        JobLanes: {
            /** Format: int64 */
            deadletter?: number;
            /** Format: int64 */
            executable?: number;
            /** Format: int64 */
            suspended?: number;
            /** Format: int64 */
            timer?: number;
        };
        MeDto: {
            engineRoles?: {
                [key: string]: string;
            };
            role?: string;
            username?: string;
        };
        NearestSiblingResponse: {
            /** Format: int32 */
            candidatesScanned?: number;
            definitionId?: string;
            /** Format: int32 */
            definitionVersion?: number;
            found?: boolean;
            processDefinitionKey?: string;
            sibling?: components["schemas"]["SiblingRef"];
        };
        NoteDto: {
            author?: string;
            body?: string;
            engineId?: string;
            /** Format: int64 */
            id?: number;
            instanceId?: string;
            /** Format: date-time */
            ts?: string;
        };
        PathActivity: {
            activityId?: string;
            activityName?: string;
            activityType?: string;
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            startTime?: string;
            unfinished?: boolean;
        };
        PathDivergence: {
            common?: string[];
            onlyInSibling?: string[];
            onlyInSubject?: string[];
            siblingPath?: components["schemas"]["PathActivity"][];
            subjectPath?: components["schemas"]["PathActivity"][];
        };
        PerEngineTriage: {
            deadletterTruncated?: boolean;
            dlqScan?: string;
            error?: string;
            ok?: boolean;
            /** Format: int32 */
            outOfScopeDeadletters?: number;
        };
        ProcessInstanceRow: {
            businessKey?: string;
            compositeId?: string;
            currentActivityOrError?: string;
            /** Format: int32 */
            definitionVersion?: number;
            endTime?: string;
            engineColor?: string;
            engineId?: string;
            engineName?: string;
            failureTime?: string;
            flags?: components["schemas"]["InstanceStatusFlags"];
            processDefinitionKey?: string;
            processDefinitionName?: string;
            processInstanceId?: string;
            protectedInstance?: boolean;
            scopeType?: string;
            startTime?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "COMPLETED" | "FAILED" | "RETRYING";
            tenantId?: string;
        };
        ResolveMatch: {
            businessKey?: string;
            compositeId?: string;
            definitionKey?: string;
            /** Format: int32 */
            definitionVersion?: number;
            endTime?: string;
            engineId?: string;
            flags?: components["schemas"]["InstanceStatusFlags"];
            /** @enum {string} */
            kind?: "PROCESS_INSTANCE" | "EXECUTION" | "TASK" | "JOB" | "BUSINESS_KEY";
            matchedId?: string;
            processInstanceId?: string;
            startTime?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "COMPLETED" | "FAILED" | "RETRYING";
        };
        ResolveResponse: {
            matches?: components["schemas"]["ResolveMatch"][];
            perEngine?: {
                [key: string]: components["schemas"]["EngineProbe"];
            };
            query?: string;
        };
        RestartInstanceRequest: {
            pinDefinitionVersion?: boolean;
            reason?: string;
            ticketId?: string;
        };
        RestartInstanceResult: {
            /** Format: uuid */
            auditId?: string;
            carriedVariables?: string[];
            correlationId?: string;
            deltaStatement?: string;
            /** Format: int32 */
            engineHttpStatus?: number;
            newProcessInstanceId?: string;
            outcome?: string;
            processDefinitionId?: string;
            skippedVariables?: {
                [key: string]: string;
            };
        };
        SearchRequest: {
            businessKey?: string;
            businessKeyLike?: string;
            currentActivity?: string;
            /** Format: int32 */
            definitionVersion?: number;
            engineIds?: string[];
            errorText?: string;
            failureTimeAfter?: string;
            failureTimeBefore?: string;
            /** Format: int32 */
            pageSize?: number;
            processDefinitionKey?: string;
            signatureHash?: string;
            sortBy?: string;
            startedAfter?: string;
            startedBefore?: string;
            statuses?: ("ACTIVE" | "SUSPENDED" | "COMPLETED" | "FAILED" | "RETRYING")[];
            variables?: components["schemas"]["VariableFilter"][];
        };
        SearchResponse: {
            criteriaEcho?: string[];
            curl?: string;
            perEngine?: {
                [key: string]: components["schemas"]["EngineResult"];
            };
            rows?: components["schemas"]["ProcessInstanceRow"][];
            statusCounts?: {
                [key: string]: number;
            };
        };
        SiblingDiffResponse: {
            path?: components["schemas"]["PathDivergence"];
            previewCappedPresent?: boolean;
            sameDefinition?: boolean;
            sibling?: components["schemas"]["InstanceRef"];
            subject?: components["schemas"]["InstanceRef"];
            timings?: components["schemas"]["TimingDelta"][];
            variables?: components["schemas"]["VariableDelta"][];
        };
        SiblingRef: {
            businessKey?: string;
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            processInstanceId?: string;
            startTime?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        TaskDto: {
            assignee?: string;
            createTime?: string;
            dueDate?: string;
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            id?: string;
            name?: string;
            owner?: string;
            state?: string;
            taskDefinitionKey?: string;
        };
        TimelineActivity: {
            activityId?: string;
            activityName?: string;
            activityType?: string;
            assignee?: string;
            calledProcessInstanceId?: string;
            children?: components["schemas"]["TimelineActivity"][];
            /** Format: int64 */
            durationMs?: number;
            endTime?: string;
            executionId?: string;
            id?: string;
            isCapped?: boolean;
            /** @enum {string} */
            liveJobState?: "FAILED" | "RETRYING";
            startTime?: string;
            taskId?: string;
        };
        TimingDelta: {
            activityId?: string;
            activityName?: string;
            /** Format: int64 */
            deltaMs?: number;
            /** Format: int64 */
            siblingMs?: number;
            /** Format: int32 */
            siblingOccurrences?: number;
            /** Format: int64 */
            subjectMs?: number;
            /** Format: int32 */
            subjectOccurrences?: number;
            subjectUnfinished?: boolean;
        };
        TriageDashboardResponse: {
            asOf?: string;
            engines?: components["schemas"]["EngineDto"][];
            errorGroups?: components["schemas"]["ErrorGroup"][];
            perEngine?: {
                [key: string]: components["schemas"]["PerEngineTriage"];
            };
            statusCounts?: {
                [key: string]: number;
            };
            statusCountsByEngine?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        TypedVariable: {
            name?: string;
            type?: string;
            value?: unknown;
        };
        VariableDelta: {
            /** @enum {string} */
            change?: "SAME" | "CHANGED" | "ONLY_IN_SUBJECT" | "ONLY_IN_SIBLING" | "DIFFER_BEYOND_PREVIEW";
            name?: string;
            sibling?: components["schemas"]["VariableDto"];
            subject?: components["schemas"]["VariableDto"];
        };
        VariableDto: {
            executionId?: string;
            name?: string;
            scope?: string;
            /** Format: int64 */
            sizeBytes?: number;
            taskId?: string;
            truncated?: boolean;
            type?: string;
            value?: unknown;
        };
        VariableEdit: {
            expectedOldValue?: unknown;
            name?: string;
            type?: string;
            value?: unknown;
        };
        VariableFilter: {
            name?: string;
            operation?: string;
            type?: string;
            value?: unknown;
        };
        WaitState: {
            activityId?: string;
            createdTime?: string;
            dueDate?: string;
            kind?: string;
            name?: string;
        };
        Warning: {
            code?: string;
            message?: string;
        };
        WhyStuck: {
            /** Format: int32 */
            deadLetterJobs?: number;
            exceptionFirstLine?: string;
            failingActivityId?: string;
            failureTime?: string;
            nextRetryDue?: string;
            /** Format: int32 */
            retriesRemaining?: number;
            /** Format: int32 */
            retryingJobs?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    operationsLog: {
        parameters: {
            query?: {
                actor?: string;
                action?: string;
                engineId?: string;
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryDto"][];
                };
            };
        };
    };
    recent: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"][];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkSubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"];
                };
            };
        };
    };
    submitErrorClass: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkErrorClassRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    submitFilter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkFilterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkJobDto"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BulkItemDto"];
                };
            };
        };
    };
    definitionAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                definitionId: string;
                verb: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionResult"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EngineDto"][];
                };
            };
        };
    };
    vitals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceDetail"];
                };
            };
        };
    };
    instanceAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
                verb: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionResult"];
                };
            };
        };
    };
    instanceActionCurl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
                verb: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionCurlResponse"];
                };
            };
        };
    };
    instanceAudit: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryDto"][];
                };
            };
        };
    };
    executeChangeState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActionResult"];
                };
            };
        };
    };
    previewChangeState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChangeStatePreview"];
                };
            };
        };
    };
    diagram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceDiagram"];
                };
            };
        };
    };
    diff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
                siblingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SiblingDiffResponse"];
                };
            };
        };
    };
    hierarchy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceHierarchy"];
                };
            };
        };
    };
    jobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceJobs"];
                };
            };
        };
    };
    externalWorkerJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExternalWorkerJobDto"][];
                };
            };
        };
    };
    jobStacktrace: {
        parameters: {
            query?: {
                lane?: string;
            };
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    nearestSibling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NearestSiblingResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteDto"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNote"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NoteDto"];
                };
            };
        };
    };
    restart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RestartInstanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestartInstanceResult"];
                };
            };
        };
    };
    tasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceTasks"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceTimeline"];
                };
            };
        };
    };
    variables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InstanceVariables"];
                };
            };
        };
    };
    variable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engineId: string;
                instanceId: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VariableDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeDto"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResolveResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TriageDashboardResponse"];
                };
            };
        };
    };
}
